inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - systemd_service_check.gemspec
    - Vagrantfile
    - vendor/**/*
    - lib/table_print-patch-pr70/*

Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Metrics/LineLength:
  Max: 90

Metrics/BlockLength:
  Enabled: false

