inherit_from: .rubocop_todo.yml
Style/AsciiComments:
  Enabled: false

Metrics/LineLength:
  Max: 90
Metrics/BlockLength:
  Enabled: false

Style/StringLiterals:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
